### ISSUE TITLE
Problem using CircuitPython version for standard Pico Pi on this board, seems to be a problem with analog pin 29 or maube any exra pins

### ISSUE THREAD

**Issue by AnderHominem** [NewAbbreviations950/Pi-Pico#1]
I was using Thonny and installed version of CircuitPython for standard Pico and wanted to connect a second joystick to the GP28 and GP29, however when I try to do so I get the error:

Traceback (most recent call last):
File "<stdin>", line 104, in <module>
AttributeError: 'module' object has no attribute 'GP29'

I would like to have some information on which version of CircuitPython I need to use to have access to the extra pins

**Comment by AnderHominem** [comment]
Okay, I just looked thru all boards available in Thonny and it seems that the Bread 2040 Dev Board is suitable, since it also has those extra pins

And I will separately clarify for noobs like me that for its use, it is neaded to write the pins differently, like this:
['__class__', '__name__', 'A0', 'A1', 'A2', 'A3', 'D0', 'D1', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D19', 'D2', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'I2C', 'MISO', 'MOSI', 'NEOPIXEL', 'RX', 'SCK', 'SCL', 'SDA', 'SPI', 'TX', 'UART', '__dict__', 'board_id']

Still having some readme with this info would be great

**Comment by NewAbbreviations950** [comment]
Yeah this board is notoriously low on documentation. Glad you figured it out!
